#
# To use the profile local, the configuration 
# smallrye.config.profile=local has to be set 
# into any valid ConfigSource.
#
# https://quarkus.io/guides/config-reference
#
# ./mvnw package -Pnative -Dquarkus.profile=local
#
# local dev usage:
# ./mvnw -Dsmallrye.config.profile=local-dev quarkus:dev

# on openshift overwrite this with env var SMALLRYE_CONFIG_PROFILE or via env var JAVA_OPTIONS=... -Dsmallrye..
smallrye:
    config:
        profile: local

"%local":
    palke:
        azure:
            sasToken: "token"
            accountName: "accName"
            containerName: "container"
        ftp:
            host: "${PALKE-SFTP-HOST}"
            user_ID138: "${PALKE-SFTP-USER-ID138}"
            password_ID138: "${PALKE-SFTP-PASSWORD-ID138}"
            user_ID166: "${PALKE-SFTP-USER-ID166}"
            password_ID166: "${PALKE-SFT_PASSWORD-ID166}"

"%openshift":
    palke:
        azure:
            sasToken: ""
            accountName: ""
            containerName: ""