#shutdown after processing
#camel.main.durationMaxIdleSeconds = 60

# disable Property-placeholders summary etc
camel.main.autoConfigurationLogSummary=false

camel.main.startup-summary-level=off

#quarkus.log.category."org.apache.camel.component.file".level=DEBUG
%dev.quarkus.datasource.sapactual.db-kind=mysql
%dev.quarkus.datasource.sapactual.username=sapfpm
%dev.quarkus.datasource.sapactual.password=sapfpm
%dev.quarkus.datasource.sapactual.jdbc.url=jdbc:mysql://localhost:3306/sapfpm
%dev.quarkus.datasource.sapactual.jdbc.max-size=16

%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.show-logs=true

%prod.quarkus.datasource.sapactual.db-kind=mysql
%prod.quarkus.datasource.sapactual.username=${DB_USER}
%prod.quarkus.datasource.sapactual.password=${DB_PASSWORD}
%prod.quarkus.datasource.sapactual.jdbc.url=jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=true&requireSSL=false
%prod.quarkus.datasource.sapactual.jdbc.max-size=16
