# Quarkus Configuration file
# key = value

#shutdown after processing
#camel.main.durationMaxIdleSeconds = 60

# disable Property-placeholders summary etc
camel.main.autoConfigurationLogSummary=false

camel.main.startup-summary-level=off

#quarkus.log.category."org.apache.camel.component.file".level=DEBUG

